### ISSUE TITLE
Clearly stating how to reproduce the results.

### ISSUE THREAD

**Issue by weihua916** [shyam196/egc#1]
Hi!

Thanks for your contribution! Currently, it is not clear to me what commands I need to run to reproduce the results. I know I can somehow figure this out [here](https://github.com/shyam196/egc/blob/main/hyperparameters.md), but we'd like the commands to be more explicit. Can you please include in your README the actual command we need to run in order to reproduce your results? Please follow the format [here](https://github.com/snap-stanford/ogb/tree/master/examples/lsc/pcqm4m). We would like one-to-one mapping from the command and the experimental results (run this commend --> users reproduce the result).

We will update the leaderboard once this is resolved. Thanks!

EDIT: You may not include any results on `ogbg-code`, as that's a bit confusing. Only reporting `ogbg-code2` is sufficient.

Best,
Weihua --- OGB Team

**Comment by shyam196** [comment]
Ah sorry. Thanks for pointing this out. This file will regenerate everything: https://github.com/shyam196/egc/blob/main/train_main_table.sh

I can split it into a separate file just for OGB submissions if you'd like, and add appropriate pointers in the readme?

**Comment by weihua916** [comment]
I see! Thanks for the pointer. Yes, having an explicit README to map the command to the expected result would be really helpful to the users.

**Comment by shyam196** [comment]
RE: code1 vs code2, I will just delete the Code-V1 results. I have them on a private repo anyway :-)

**Comment by shyam196** [comment]
@weihua916 I have added an explicit comment on what those two retraining scripts do, and deleted the code-v1 hyperparameters. Let me know if you'd like me to add anything else!

**Comment by weihua916** [comment]
Awesome! Looks great. It is very clear now. I have updated the leaderboards. Thanks!
